apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: play-nginx
  template:
    metadata:
      labels:
        app: play-nginx
    spec:
      containers:
        - name: play-nginx
          image: play-nginx:v0
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: play-nginx
spec:
  type: ClusterIP
  selector:
    app: play-nginx
  ports:
    - protocol: TCP
      port: 40480
      targetPort: 80
