apiVersion: v1
kind: ServiceAccount
metadata:
  name: song-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: song-admin-binding
subjects:
  - kind: ServiceAccount
    name: song-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: live-gate-song
spec:
  serviceName: "live-gate-song"
  replicas: 1
  selector:
    matchLabels:
      app: live-gate-song
  template:
    metadata:
      labels:
        app: live-gate-song
    spec:
      serviceAccountName: song-sa
      containers:
        - name: live-gate-song
          image: live-gate-song:v0
          imagePullPolicy: Never
          ports:
            - containerPort: 22
